"use client";

import { useState } from "react";
import { ArrowRight, Gavel, Scale, ShieldCheck, Sparkles, Loader2, Send, Users, FileText, Landmark, GitBranch, MessageSquare } from "lucide-react";

const API_URL = process.env.NEXT_PUBLIC_API_URL || "http://localhost:8000";
const phases = ["Abertura", "Autor", "Defesa", "Testemunhas", "Perícia", "MP", "Alegações", "Deliberação", "Sentença"];
type Role = "spectator" | "plaintiff_attorney" | "defense_attorney" | "prosecutor" | "judge" | "juror";
const roles: { id: Role; title: string; description: string }[] = [
  { id: "spectator", title: "Observador", description: "Acompanhe o julgamento sem representar uma parte." },
  { id: "plaintiff_attorney", title: "Advogado do autor", description: "Atue pela parte autora durante a simulação." },
  { id: "defense_attorney", title: "Advogado do réu", description: "Atue pela defesa da parte ré." },
  { id: "prosecutor", title: "Promotor de Justiça", description: "Atue pelo Ministério Público quando cabível." },
  { id: "judge", title: "Magistrado", description: "Conduza a audiência e profira decisões na simulação." },
  { id: "juror", title: "Jurados", description: "Participe da deliberação em simulações com Tribunal do Júri." },
];

export default function Home() {
  const [started, setStarted] = useState(false), [inChat, setInChat] = useState(false), [caseText, setCaseText] = useState(""), [area, setArea] = useState("consumer"), [plaintiff, setPlaintiff] = useState("Autor da simulação"), [defendant, setDefendant] = useState("Réu da simulação"), [includeMP, setIncludeMP] = useState(false), [jury, setJury] = useState(false), [selectedRole, setSelectedRole] = useState<Role>("spectator"), [processId, setProcessId] = useState(""), [processNumber, setProcessNumber] = useState(""), [characters, setCharacters] = useState<any[]>([]), [messages, setMessages] = useState<any[]>([]), [chatText, setChatText] = useState(""), [phase, setPhase] = useState("opening"), [panel, setPanel] = useState<"details" | "people" | "documents" | "appeals" | null>(null), [loading, setLoading] = useState(false), [error, setError] = useState("");

  async function startProcess() {
    if (!caseText.trim()) return; setLoading(true); setError("");
    try { const response = await fetch(`${API_URL}/api/v1/processes`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ area, plaintiff, defendant, facts: caseText.trim(), include_mp: includeMP, jury }) }); if (!response.ok) throw new Error("Não foi possível criar o processo."); const process = await response.json(); setProcessId(process.id); setProcessNumber(process.number); setCharacters(process.characters || []); setStarted(true); }
    catch (err) { setError(err instanceof Error ? err.message : "Erro ao iniciar o processo."); } finally { setLoading(false); }
  }

  async function enterCourtroom() {
    setLoading(true); setError("");
    try { const response = await fetch(`${API_URL}/api/v1/processes/${processId}/courtroom/session`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ role: selectedRole }) }); const data = await response.json(); if (!response.ok) throw new Error(data.detail || "Não foi possível abrir a sessão."); setMessages(data.messages || []); setPhase(data.phase || "opening"); setInChat(true); }
    catch (err) { setError(err instanceof Error ? err.message : "Erro ao abrir a sessão."); } finally { setLoading(false); }
  }

  async function sendMessage() {
    if (!chatText.trim()) return; const content = chatText.trim(); setChatText(""); setError("");
    try { const response = await fetch(`${API_URL}/api/v1/processes/${processId}/courtroom/session/${selectedRole}/messages`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ content }) }); const data = await response.json(); if (!response.ok) throw new Error(data.detail || "Não foi possível enviar a mensagem."); setMessages(prev => [...prev, data.message, ...(data.ruling ? [data.ruling] : [])].filter(Boolean)); }
    catch (err) { setError(err instanceof Error ? err.message : "Erro ao enviar mensagem."); }
  }

  async function advancePhase() {
    setLoading(true); setError("");
    try { const response = await fetch(`${API_URL}/api/v1/processes/${processId}/courtroom/session/${selectedRole}/advance`, { method: "POST" }); const data = await response.json(); if (!response.ok) throw new Error(data.detail || "Não foi possível avançar a audiência."); setPhase(data.phase); setMessages(prev => [...prev, data.message]); }
    catch (err) { setError(err instanceof Error ? err.message : "Erro ao avançar a audiência."); } finally { setLoading(false); }
  }

  async function loadParticipants() {
    try { const response = await fetch(`${API_URL}/api/v1/processes/${processId}/courtroom/participants`); const data = await response.json(); if (!response.ok) throw new Error(data.detail || "Não foi possível carregar os participantes."); setCharacters(data.participants || []); setPanel("people"); }
    catch (err) { setError(err instanceof Error ? err.message : "Erro ao carregar participantes."); }
  }

  const roleName = roles.find(r => r.id === selectedRole)?.title || "Observador";
  const areaName = { consumer: "Direito do Consumidor", civil: "Direito Civil", labor: "Direito do Trabalho", criminal: "Direito Penal" }[area as "consumer" | "civil" | "labor" | "criminal"];
  const phaseIndex = Math.max(0, ["opening", "plaintiff", "defense", "witness_plaintiff", "witness_defense", "expert", "mp", "closing", "deliberation", "judgment", "closed"].indexOf(phase));

  return <main className="shell">
    <header className="topbar"><div className="brand"><div className="brand-mark"><Scale size={20}/></div><div><strong>TRIBUNAL VIRTUAL</strong><span>Simulação jurídica</span></div></div><div className="status"><span className="status-dot"/> Sistema operacional</div></header>
    {!started && <section className="hero"><div className="eyebrow"><Sparkles size={15}/> INTELIGÊNCIA ARTIFICIAL + DIREITO BRASILEIRO</div><h1>Um tribunal para<br/><em>simular casos jurídicos.</em></h1><p className="lead">Crie um processo e entre em uma sala de julgamento onde você escolhe seu papel e interage com personagens jurídicos fictícios.</p><div className="features"><div><Gavel size={19}/><span><b>Tribunal interativo</b>Chat, audiência, testemunhas e participantes.</span></div><div><ShieldCheck size={19}/><span><b>Processo por etapas</b>Recursos e instâncias fazem parte da simulação.</span></div></div><div className="case-card"><div className="card-label">NOVO PROCESSO</div><label>Área jurídica</label><select value={area} onChange={e=>setArea(e.target.value)}><option value="consumer">Direito do Consumidor</option><option value="civil">Direito Civil</option><option value="labor">Direito do Trabalho</option><option value="criminal">Direito Penal</option></select><label>Autor</label><input value={plaintiff} onChange={e=>setPlaintiff(e.target.value)}/><label>Réu</label><input value={defendant} onChange={e=>setDefendant(e.target.value)}/><label>Relato dos fatos</label><textarea value={caseText} onChange={e=>setCaseText(e.target.value)} placeholder="Descreva os fatos do caso que será simulado..." rows={5}/><label className="checkbox-row"><input type="checkbox" checked={includeMP} onChange={e=>setIncludeMP(e.target.checked)}/><span><b>Incluir Ministério Público</b><small>Ative quando houver hipótese de atuação do MP.</small></span></label>{area === "criminal" && <label className="checkbox-row"><input type="checkbox" checked={jury} onChange={e=>setJury(e.target.checked)}/><span><b>Tribunal do Júri</b><small>Inclui conselho de sentença com 7 jurados.</small></span></label>}{error && <div className="error">{error}</div>}<button onClick={startProcess} disabled={!caseText.trim() || loading}>{loading ? <><Loader2 size={17}/> Criando processo...</> : <>Criar processo <ArrowRight size={17}/></>}</button><small>Ambiente educacional. Nomes, personagens e decisões são fictícios.</small></div></section>}
    {started && !inChat && <section className="role-page"><div className="process-head"><div><div className="eyebrow">PROCESSO CRIADO</div><h2>Processo nº {processNumber}</h2><p>{areaName} · escolha seu papel antes de entrar na sala</p></div></div><div className="role-grid">{roles.map(role=><button key={role.id} className={selectedRole===role.id?"role-card selected":"role-card"} onClick={()=>setSelectedRole(role.id)}><strong>{role.title}</strong><span>{role.description}</span></button>)}</div>{error && <div className="error">{error}</div>}<button className="primary-action" onClick={enterCourtroom} disabled={loading}>{loading ? "Abrindo sala..." : <>Entrar na sala de julgamento <MessageSquare size={17}/></>}</button><p className="fictional-note">Você poderá consultar o processo, participantes, documentos, testemunhas, jurados e recursos durante a sessão.</p></section>}
    {started && inChat && <section className="courtroom"><div className="court-head"><div><div className="eyebrow">SALA DE JULGAMENTO · 1ª INSTÂNCIA</div><h2>Processo nº {processNumber}</h2><p>{roleName} · {areaName} · fase: {phases[Math.min(phaseIndex, phases.length-1)]}</p></div><button className="ghost" onClick={()=>setInChat(false)}>Trocar papel</button></div><div className="court-tools"><button onClick={()=>setPanel(panel==="details"?null:"details")}><FileText size={16}/> Processo</button><button onClick={loadParticipants}><Users size={16}/> Participantes</button><button onClick={()=>setPanel(panel==="documents"?null:"documents")}><Landmark size={16}/> Audiência</button><button onClick={()=>setPanel(panel==="appeals"?null:"appeals")}><GitBranch size={16}/> Recursos e instâncias</button></div>{panel && <aside className="court-panel">{panel==="details" && <><h3>Detalhes do processo</h3><p><b>Classe:</b> Simulação de {areaName}</p><p><b>Autor:</b> {plaintiff}</p><p><b>Réu:</b> {defendant}</p><p><b>Instância:</b> {phaseIndex >= 9 ? "Decisão" : "1ª instância"}</p></>}{panel==="people" && <><h3>Pessoas no julgamento</h3>{characters.map((c,i)=><div className="person" key={c.id || i}><b>{c.title} {c.name}</b><small>{c.profession || (c.role === "juror" ? "Conselho de Sentença" : "Participante fictício")}</small></div>)}</>}{panel==="documents" && <><h3>Audiência e instrução</h3><div className="person"><b>Testemunhas</b><small>Depoimentos e perguntas são realizados na fase de instrução.</small></div><div className="person"><b>Perícia</b><small>O perito pode esclarecer questões que dependam de conhecimento técnico.</small></div><button className="secondary-action" onClick={advancePhase} disabled={loading}>Avançar fase</button></>}{panel==="appeals" && <><h3>Recursos e instâncias</h3><p>Após uma decisão recorrível, a parte legitimada poderá protocolar o recurso cabível.</p><button className="secondary-action">Preparar recurso</button><p className="side-note">O recurso passa por análise de admissibilidade antes do julgamento pelo órgão competente.</p></>}</aside>}
      <div className="phase-strip">{phases.map((p,i)=><span className={i<=phaseIndex?"active":""} key={p}>{p}</span>)}</div><div className="chat-window"><div className="chat-title"><span><MessageSquare size={17}/><b>Plenário virtual</b></span><small>Debate livre · ordem processual controlada</small></div><div className="messages">{messages.map((m:any,i:number)=><div className={m.kind==="user"?"message user":"message"} key={m.id || i}><small>{m.sender || m.actor}</small><p>{m.content}</p>{m.assessment && m.assessment !== "normal" && <span className="message-badge">{m.assessment}</span>}</div>)}</div><div className="composer"><textarea value={chatText} onChange={e=>setChatText(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();sendMessage()}}} placeholder="Digite sua manifestação, pergunta ou intervenção..." rows={2}/><button onClick={sendMessage} disabled={!chatText.trim()}><Send size={17}/> Enviar</button></div></div>{error && <div className="error">{error}</div>}<div className="notice"><Landmark size={15}/> <span>Uma intervenção fora da vez não é automaticamente descartada: se apresentar pertinência relevante, o juízo poderá conceder a palavra e registrar a manifestação.</span></div></section>}
  </main>;
}
